In [1]:
# Dependencies
import pandas as pd
import json
import requests
import datetime as dt

# import sqlalchemy
# from sqlalchemy.ext.automap import automap_base
# from sqlalchemy.orm import Session
# from sqlalchemy import create_engine, func, inspect
# import sqlite3

In [2]:
with open('Resources/ColoCitiesDataClean.csv') as f:
    print(f)

<_io.TextIOWrapper name='Resources/ColoCitiesDataClean.csv' mode='r' encoding='UTF-8'>

In [3]:
latlon_df = pd.read_csv("Resources/ColoCitiesDataClean.csv", encoding='cp1252')
latlon_df.head()

  Place Name        lat         lon Population    Area
0    Aguilar  37.403611 -104.655000        480   1.016
1      Akron  40.163333 -103.220278      1,723   7.180
2    Alamosa  37.475278 -105.876944      9,591  19.871
3       Alma  39.285833 -106.066944        313   1.129
4   Antonito  37.076111 -106.010278        747   1.105

In [4]:
# Save config information
url = "http://api.openweathermap.org/data/2.5/air_pollution?"
api_key= "90d059c74bd13bcc4087b66e982c1bf1"
lat=37.40361111
lon=-104.655

#Build URL
query_url = f"{url}lat={lat}&lon={lon}&appid={api_key}"

#Query API
air_response = requests.get(query_url).json()

#Test API response
print(air_response)

{'coord': {'lon': -104.655, 'lat': 37.4036}, 'list': [{'main': {'aqi': 4}, 'components': {'co': 223.64, 'no': 0, 'no2': 2.36, 'o3': 97.28, 'so2': 0.48, 'pm2_5': 32.87, 'pm10': 48.14, 'nh3': 2.38}, 'dt': 1628398800}]}

In [5]:
# Save config information
url = "http://api.openweathermap.org/data/2.5/air_pollution?"
api_key= "90d059c74bd13bcc4087b66e982c1bf1"

# Counter to sort through response
number = 0
group = 1

# Create DataFrame
## Update PM names to remove spaces
columns= ["City","Date", "lat", "lon", "AQI", "CO", "NO", "NO2", "O3", "SO2", "PM25", "PM10", "NH3"]
air_df = pd.DataFrame(columns=columns)

for index, row in latlon_df.iterrows():
    
    lat = row["lat"]
    lon = row["lon"]
    #print(lat)
    #print(lon)
    query_url = f"{url}lat={lat}&lon={lon}&appid={api_key}"
    air_response = requests.get(query_url).json()
 
    try:
        print(f"Processing Record {number}  of Group {group} | {lat}{lon}.")
        
        print (query_url) 
    
        air_api_values= {
            "City" : row["Place Name"],
            "Population": row["Population"],
            "Date" : air_response["list"][0]["dt"],  
             "lon" : air_response["coord"]["lon"],
             "lat" : air_response["coord"]["lat"],
             "AQI" : air_response["list"][0]["main"]["aqi"],
             "CO" : air_response["list"][0]["components"]["co"],  
             "NO" : air_response["list"][0]["components"]["no"],
             "NO2" : air_response["list"][0]["components"]["no2"],  
             "O3" : air_response["list"][0]["components"]["o3"],
             "SO2" : air_response["list"][0]["components"]["so2"],
            #Update names of PM so they don't have spaces
             "PM25" : air_response["list"][0]["components"]["pm2_5"],
             "PM10" : air_response["list"][0]["components"]["pm10"],
             "NH3" : air_response["list"][0]["components"]["nh3"]
           }
        air_df= air_df.append(air_api_values, ignore_index=True)
        
    except:
        print(f"not working")
        pass
        
    
    # To save money on API calls
    number = number + 1
    if number == 50:
        number= 0
        group = group + 1

Processing Record 0  of Group 1 | 37.40361111-104.655.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.40361111&lon=-104.655&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 1  of Group 1 | 40.16333333-103.22027779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.16333333&lon=-103.22027779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 2  of Group 1 | 37.47527778-105.87694440000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.47527778&lon=-105.87694440000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 3  of Group 1 | 39.28583333-106.06694440000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.28583333&lon=-106.06694440000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 4  of Group 1 | 37.07611111-106.0102778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.07611111&lon=-106.0102778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 5  of Group 1 | 39.28444444-103.2741667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.28444444&lon=-103.2741667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 6  of Group 1 | 39.83194444-105.15111110000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.83194444&lon=-105.15111110000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 7  of Group 1 | 39.195-106.83666670000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.195&lon=-106.83666670000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 8  of Group 1 | 40.58916667-104.7391667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.58916667&lon=-104.7391667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 9  of Group 1 | 39.70833333-104.7238889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.70833333&lon=-104.7238889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 10  of Group 1 | 39.64416667-106.51305559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.64416667&lon=-106.51305559999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 11  of Group 1 | 39.36638889-107.0413889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.36638889&lon=-107.0413889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 12  of Group 1 | 37.23416667-107.59527779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.23416667&lon=-107.59527779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 13  of Group 1 | 39.73666667-104.4286111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.73666667&lon=-104.4286111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 14  of Group 1 | 40.30722222-105.0425.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.30722222&lon=-105.0425&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 15  of Group 1 | 39.30388889-102.4233333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.30388889&lon=-102.4233333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 16  of Group 1 | 39.80416667-105.495.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.80416667&lon=-105.495&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 17  of Group 1 | 37.43916667-105.5136111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.43916667&lon=-105.5136111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 18  of Group 1 | 39.43583333-106.03527779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.43583333&lon=-106.03527779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 19  of Group 1 | 38.29666667-106.14194440000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.29666667&lon=-106.14194440000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 20  of Group 1 | 38.24944444-104.25805559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.24944444&lon=-104.25805559999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 21  of Group 1 | 40.02472222-105.2525.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.02472222&lon=-105.2525&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 22  of Group 1 | 39.62527778-105.0511111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.62527778&lon=-105.0511111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 23  of Group 1 | 37.01555556-103.8838889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.01555556&lon=-103.8838889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 24  of Group 1 | 39.49944444-106.04333329999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.49944444&lon=-106.04333329999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 25  of Group 1 | 39.97166667-104.79638890000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.97166667&lon=-104.79638890000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 26  of Group 1 | 38.41361111-105.19083329999998.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.41361111&lon=-105.19083329999998&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 27  of Group 1 | 39.95416667-105.05277779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.95416667&lon=-105.05277779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 28  of Group 1 | 40.26-103.6322222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.26&lon=-103.6322222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 29  of Group 1 | 38.83194444-106.1386111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.83194444&lon=-106.1386111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 30  of Group 1 | 39.30416667-102.2713889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.30416667&lon=-102.2713889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 31  of Group 1 | 39.03444444-104.2994444.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.03444444&lon=-104.2994444&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 32  of Group 1 | 37.10472222-102.57888890000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.10472222&lon=-102.57888890000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 33  of Group 1 | 38.44305556-105.22027779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.44305556&lon=-105.22027779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 34  of Group 1 | 39.74416667-107.3391667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.74416667&lon=-107.3391667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 35  of Group 1 | 39.395-107.21472220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.395&lon=-107.21472220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 36  of Group 1 | 39.4625-104.87055559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.4625&lon=-104.87055559999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 37  of Group 1 | 39.37611111-104.8536111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.37611111&lon=-104.8536111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 38  of Group 1 | 38.89416667-107.92555559999998.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.89416667&lon=-107.92555559999998&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 39  of Group 1 | 39.5925-104.8672222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.5925&lon=-104.8672222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 40  of Group 1 | 37.75111111-106.11055559999998.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.75111111&lon=-106.11055559999998&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 41  of Group 1 | 39.79472222-105.51194440000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.79472222&lon=-105.51194440000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 42  of Group 1 | 38.1075-103.5111111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.1075&lon=-103.5111111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 43  of Group 1 | 39.6375-104.94805559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.6375&lon=-104.94805559999999&appid=90d059c74bd13bcc4087b66e982c1bf1

Processing Record 44  of Group 1 | 38.81916667-102.35194440000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.81916667&lon=-102.35194440000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 45  of Group 1 | 38.36222222-105.1422222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.36222222&lon=-105.1422222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 46  of Group 1 | 37.14416667-104.6216667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.14416667&lon=-104.6216667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 47  of Group 1 | 39.24-107.96361110000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.24&lon=-107.96361110000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 48  of Group 1 | 38.8675-104.7605556.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.8675&lon=-104.7605556&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 49  of Group 1 | 39.59944444-105.03527779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.59944444&lon=-105.03527779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 0  of Group 2 | 39.86416667-104.8430556.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.86416667&lon=-104.8430556&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 1  of Group 2 | 37.35027778-108.57666670000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.35027778&lon=-108.57666670000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 2  of Group 2 | 40.51694444-107.5552778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.51694444&lon=-107.5552778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 3  of Group 2 | 38.705-107.60972220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.705&lon=-107.60972220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 4  of Group 2 | 37.84861111-106.92527779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.84861111&lon=-106.92527779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 5  of Group 2 | 38.8675-106.9772222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.8675&lon=-106.9772222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 6  of Group 2 | 37.99444444-105.69611110000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.99444444&lon=-105.69611110000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 7  of Group 2 | 38.74666667-105.185.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.74666667&lon=-105.185&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 8  of Group 2 | 40.85888889-102.8013889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.85888889&lon=-102.8013889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 9  of Group 2 | 38.19361111-103.85972220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.19361111&lon=-103.85972220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 10  of Group 2 | 40.06222222-104.9477778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.06222222&lon=-104.9477778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 11  of Group 2 | 39.31027778-108.205.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.31027778&lon=-108.205&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 12  of Group 2 | 39.615-104.0433333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.615&lon=-104.0433333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 13  of Group 2 | 37.67833333-106.3538889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.67833333&lon=-106.3538889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 14  of Group 2 | 38.75611111-108.07722220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.75611111&lon=-108.07722220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 15  of Group 2 | 39.76194444-104.8761111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.76194444&lon=-104.8761111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 16  of Group 2 | 39.62138889-106.03944440000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.62138889&lon=-106.03944440000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 17  of Group 2 | 40.23972222-109.00666670000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.23972222&lon=-109.00666670000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 18  of Group 2 | 37.47416667-108.5.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.47416667&lon=-108.5&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 19  of Group 2 | 37.76694444-108.9072222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.76694444&lon=-108.9072222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 20  of Group 2 | 37.26583333-107.87833329999998.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.26583333&lon=-107.87833329999998&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 21  of Group 2 | 38.48138889-102.77972220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.48138889&lon=-102.77972220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 22  of Group 2 | 39.63666667-106.8125.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.63666667&lon=-106.8125&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 23  of Group 2 | 40.52555556-104.7130556.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.52555556&lon=-104.7130556&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 24  of Group 2 | 40.11222222-102.4883333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.11222222&lon=-102.4883333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 25  of Group 2 | 39.75083333-105.0625.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.75083333&lon=-105.0625&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 26  of Group 2 | 39.35888889-104.6194444.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.35888889&lon=-104.6194444&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 27  of Group 2 | 39.75944444-105.68222220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.75944444&lon=-105.68222220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 28  of Group 2 | 39.64666667-104.99416670000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.64666667&lon=-104.99416670000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 29  of Group 2 | 40.04027778-105.04.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.04027778&lon=-105.04&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 30  of Group 2 | 40.37-105.52166670000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.37&lon=-105.52166670000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 31  of Group 2 | 40.36611111-104.7388889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.36611111&lon=-104.7388889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 32  of Group 2 | 39.22444444-105.99666670000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.22444444&lon=-105.99666670000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 33  of Group 2 | 39.865-105.01555559999998.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.865&lon=-105.01555559999998&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 34  of Group 2 | 40.15638889-104.94944440000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.15638889&lon=-104.94944440000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 35  of Group 2 | 39.29472222-103.0758333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.29472222&lon=-103.0758333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 36  of Group 2 | 40.68194444-102.83972220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.68194444&lon=-102.83972220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 37  of Group 2 | 38.38361111-105.1113889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.38361111&lon=-105.1113889&appid=90d059c74bd13bcc4087b66e982c1bf1

Processing Record 38  of Group 2 | 40.5475-105.06555559999998.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.5475&lon=-105.06555559999998&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 39  of Group 2 | 40.08277778-104.8069444.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.08277778&lon=-104.8069444&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 40  of Group 2 | 40.25361111-103.7902778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.25361111&lon=-103.7902778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 41  of Group 2 | 38.68833333-104.6827778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.68833333&lon=-104.6827778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 42  of Group 2 | 38.13055556-104.02638890000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.13055556&lon=-104.02638890000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 43  of Group 2 | 39.58805556-104.7858333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.58805556&lon=-104.7858333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 44  of Group 2 | 39.93027778-105.8030556.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.93027778&lon=-105.8030556&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 45  of Group 2 | 40.10888889-104.97.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.10888889&lon=-104.97&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 46  of Group 2 | 39.57916667-106.09166670000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.57916667&lon=-106.09166670000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 47  of Group 2 | 39.15472222-108.73055559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.15472222&lon=-108.73055559999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 48  of Group 2 | 40.39472222-104.6894444.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.39472222&lon=-104.6894444&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 49  of Group 2 | 39.27833333-103.49861109999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.27833333&lon=-103.49861109999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 0  of Group 3 | 39.71805556-105.69416670000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.71805556&lon=-105.69416670000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 1  of Group 3 | 40.28416667-104.7819444.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.28416667&lon=-104.7819444&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 2  of Group 3 | 39.70361111-104.9352778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.70361111&lon=-104.9352778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 3  of Group 3 | 39.54555556-107.3347222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.54555556&lon=-107.3347222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 4  of Group 3 | 39.74055556-105.21194440000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.74055556&lon=-105.21194440000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 5  of Group 3 | 38.06305556-102.3116667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.06305556&lon=-102.3116667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 6  of Group 3 | 40.06472222-105.91944440000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.06472222&lon=-105.91944440000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 7  of Group 3 | 39.08777778-108.5675.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.08777778&lon=-108.5675&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 8  of Group 3 | 40.25027778-105.82305559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.25027778&lon=-105.82305559999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 9  of Group 3 | 40.415-104.7705556.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.415&lon=-104.7705556&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 10  of Group 3 | 38.93444444-105.0238889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.93444444&lon=-105.0238889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 11  of Group 3 | 39.61527778-104.91305559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.61527778&lon=-104.91305559999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 12  of Group 3 | 40.86916667-104.2258333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.86916667&lon=-104.2258333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 13  of Group 3 | 38.54805556-106.9247222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.54805556&lon=-106.9247222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 14  of Group 3 | 39.62861111-106.935.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.62861111&lon=-106.935&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 15  of Group 3 | 38.12111111-102.2216667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.12111111&lon=-102.2216667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 16  of Group 3 | 38.4525-103.165.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.4525&lon=-103.165&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 17  of Group 3 | 40.64194444-102.6297222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.64194444&lon=-102.6297222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 18  of Group 3 | 40.485-107.23916670000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.485&lon=-107.23916670000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 19  of Group 3 | 40.32444444-103.5222222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.32444444&lon=-103.5222222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 20  of Group 3 | 38.05527778-102.12472220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.05527778&lon=-102.12472220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 21  of Group 3 | 40.58194444-102.2975.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.58194444&lon=-102.2975&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 22  of Group 3 | 37.74611111-105.87777779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.74611111&lon=-105.87777779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 23  of Group 3 | 40.075-106.10305559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.075&lon=-106.10305559999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 24  of Group 3 | 38.79888889-107.71333329999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.79888889&lon=-107.71333329999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 25  of Group 3 | 40.09-104.6208333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.09&lon=-104.6208333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 26  of Group 3 | 39.13611111-103.4730556.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.13611111&lon=-103.4730556&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 27  of Group 3 | 39.74444444-105.5.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.74444444&lon=-105.5&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 28  of Group 3 | 37.11805556-107.6375.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.11805556&lon=-107.6375&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 29  of Group 3 | 40.75916667-103.06611109999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.75916667&lon=-103.06611109999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 30  of Group 3 | 40.11833333-105.39166670000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.11833333&lon=-105.39166670000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 31  of Group 3 | 40.34972222-104.94833329999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.34972222&lon=-104.94833329999999&appid=90d059c74bd13bcc4087b66e982c1bf1

Processing Record 32  of Group 3 | 40.985-102.2627778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.985&lon=-102.2627778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 33  of Group 3 | 40.13277778-104.53805559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.13277778&lon=-104.53805559999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 34  of Group 3 | 40.39083333-104.5794444.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.39083333&lon=-104.5794444&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 35  of Group 3 | 37.24694444-103.3533333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.24694444&lon=-103.3533333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 36  of Group 3 | 39.34361111-104.45777779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.34361111&lon=-104.45777779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 37  of Group 3 | 38.76277778-102.7952778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.76277778&lon=-102.7952778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 38  of Group 3 | 40.05666667-106.37833329999998.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.05666667&lon=-106.37833329999998&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 39  of Group 3 | 37.27361111-105.9597222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.27361111&lon=-105.9597222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 40  of Group 3 | 37.97916667-103.54722220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.97916667&lon=-103.54722220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 41  of Group 3 | 37.50861111-105.00861110000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.50861111&lon=-105.00861110000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 42  of Group 3 | 39.99472222-105.0997222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.99472222&lon=-105.0997222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 43  of Group 3 | 38.03-107.31055559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.03&lon=-107.31055559999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 44  of Group 3 | 39.78027778-105.0577778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.78027778&lon=-105.0577778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 45  of Group 3 | 39.69777778-105.1172222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.69777778&lon=-105.1172222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 46  of Group 3 | 38.07388889-102.61527779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.07388889&lon=-102.61527779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 47  of Group 3 | 39.23194444-104.8922222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.23194444&lon=-104.8922222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 48  of Group 3 | 38.06944444-103.22361109999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.06944444&lon=-103.22361109999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 49  of Group 3 | 40.34833333-104.70611109999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.34833333&lon=-104.70611109999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 0  of Group 4 | 39.24722222-106.29333329999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.24722222&lon=-106.29333329999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 1  of Group 4 | 39.26527778-103.6855556.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.26527778&lon=-103.6855556&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 2  of Group 4 | 39.59138889-105.0188889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.59138889&lon=-105.0188889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 3  of Group 4 | 40.01166667-104.7272222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.01166667&lon=-104.7272222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 4  of Group 4 | 40.26972222-103.82888890000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.26972222&lon=-103.82888890000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 5  of Group 4 | 39.53083333-104.87083329999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.53083333&lon=-104.87083329999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 6  of Group 4 | 40.16861111-105.10055559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.16861111&lon=-105.10055559999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 7  of Group 4 | 39.97111111-105.14416670000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.97111111&lon=-105.14416670000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 8  of Group 4 | 40.41666667-105.06222220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.41666667&lon=-105.06222220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 9  of Group 4 | 40.22305556-105.26916670000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.22305556&lon=-105.26916670000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 10  of Group 4 | 37.17388889-105.93722220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.17388889&lon=-105.93722220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 11  of Group 4 | 37.34666667-108.2938889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.34666667&lon=-108.2938889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 12  of Group 4 | 38.8575-104.91277779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.8575&lon=-104.91277779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 13  of Group 4 | 38.10888889-103.8666667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.10888889&lon=-103.8666667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 14  of Group 4 | 39.07166667-107.19083329999998.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.07166667&lon=-107.19083329999998&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 15  of Group 4 | 40.23166667-104.9911111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.23166667&lon=-104.9911111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 16  of Group 4 | 40.05-107.8947222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.05&lon=-107.8947222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 17  of Group 4 | 40.48361111-103.3536111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.48361111&lon=-103.3536111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 18  of Group 4 | 40.31138889-104.85611109999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.31138889&lon=-104.85611109999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 19  of Group 4 | 39.54611111-106.38694440000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.54611111&lon=-106.38694440000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 20  of Group 4 | 38.00277778-105.9063889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.00277778&lon=-105.9063889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 21  of Group 4 | 37.57888889-106.15.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.57888889&lon=-106.15&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 22  of Group 4 | 39.58138889-105.8677778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.58138889&lon=-105.8677778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 23  of Group 4 | 38.46888889-107.8588889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.46888889&lon=-107.8588889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 24  of Group 4 | 39.07361111-104.8466667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.07361111&lon=-104.8466667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 25  of Group 4 | 39.63694444-105.20055559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.63694444&lon=-105.20055559999999&appid=90d059c74bd13bcc4087b66e982c1bf1

Processing Record 26  of Group 4 | 38.90833333-106.96055559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.90833333&lon=-106.96055559999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 27  of Group 4 | 39.77472222-105.05666670000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.77472222&lon=-105.05666670000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 28  of Group 4 | 37.9325-107.8577778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.9325&lon=-107.8577778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 29  of Group 4 | 38.21833333-108.56666670000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.21833333&lon=-108.56666670000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 30  of Group 4 | 39.96333333-105.5072222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.96333333&lon=-105.5072222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 31  of Group 4 | 39.5775-107.5266667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.5775&lon=-107.5266667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 32  of Group 4 | 39.91083333-104.97833329999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.91083333&lon=-104.97833329999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 33  of Group 4 | 38.12916667-108.29194440000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.12916667&lon=-108.29194440000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 34  of Group 4 | 38.26666667-108.5486111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.26666667&lon=-108.5486111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 35  of Group 4 | 40.71388889-104.7888889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.71388889&lon=-104.7888889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 36  of Group 4 | 40.27416667-106.9575.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.27416667&lon=-106.9575&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 37  of Group 4 | 38.60833333-107.98333329999998.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.60833333&lon=-107.98333329999998&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 38  of Group 4 | 38.16638889-103.9444444.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.16638889&lon=-103.9444444&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 39  of Group 4 | 37.85694444-107.8311111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.85694444&lon=-107.8311111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 40  of Group 4 | 38.81444444-107.97055559999998.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.81444444&lon=-107.97055559999998&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 41  of Group 4 | 38.22083333-103.7566667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.22083333&lon=-103.7566667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 42  of Group 4 | 40.15-102.96222220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.15&lon=-102.96222220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 43  of Group 4 | 38.0275-107.67333329999998.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.0275&lon=-107.67333329999998&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 44  of Group 4 | 40.96083333-102.3883333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.96083333&lon=-102.3883333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 45  of Group 4 | 37.2675-107.03055559999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.2675&lon=-107.03055559999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 46  of Group 4 | 39.10833333-108.35722220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.10833333&lon=-108.35722220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 47  of Group 4 | 39.11527778-104.9061111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.11527778&lon=-104.9061111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 48  of Group 4 | 40.61277778-102.4716667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.61277778&lon=-102.4716667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 49  of Group 4 | 38.86972222-107.59194440000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.86972222&lon=-107.59194440000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 0  of Group 5 | 39.45083333-108.0530556.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.45083333&lon=-108.0530556&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 1  of Group 5 | 39.50833333-104.7752778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.50833333&lon=-104.7752778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 2  of Group 5 | 40.96194444-103.1138889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.96194444&lon=-103.1138889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 3  of Group 5 | 40.64111111-104.77027779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.64111111&lon=-104.77027779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 4  of Group 5 | 38.60861111-106.515.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.60861111&lon=-106.515&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 5  of Group 5 | 40.22194444-104.8341667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.22194444&lon=-104.8341667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 6  of Group 5 | 38.51416667-106.09416670000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.51416667&lon=-106.09416670000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 7  of Group 5 | 37.37-102.85861109999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.37&lon=-102.85861109999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 8  of Group 5 | 38.27-104.61138890000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.27&lon=-104.61138890000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 9  of Group 5 | 39.12222222-104.16722220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.12222222&lon=-104.16722220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 10  of Group 5 | 40.08611111-108.77944440000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.08611111&lon=-108.77944440000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 11  of Group 5 | 40.60805556-103.84361109999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.60805556&lon=-103.84361109999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 12  of Group 5 | 39.50916667-106.37.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.50916667&lon=-106.37&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 13  of Group 5 | 37.68916667-108.03166670000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.68916667&lon=-108.03166670000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 14  of Group 5 | 38.15722222-107.7547222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.15722222&lon=-107.7547222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 15  of Group 5 | 39.53611111-107.7727778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.53611111&lon=-107.7727778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 16  of Group 5 | 38.36444444-105.1647222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.36444444&lon=-105.1647222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 17  of Group 5 | 38.05-103.7225.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.05&lon=-103.7225&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 18  of Group 5 | 37.17194444-105.98527779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.17194444&lon=-105.98527779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 19  of Group 5 | 37.92138889-104.93194440000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.92138889&lon=-104.93194440000002&appid=90d059c74bd13bcc4087b66e982c1bf1

Processing Record 20  of Group 5 | 38.08638889-106.1411111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.08638889&lon=-106.1411111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 21  of Group 5 | 38.53-105.9977778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.53&lon=-105.9977778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 22  of Group 5 | 37.2025-105.4225.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.2025&lon=-105.4225&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 23  of Group 5 | 37.2575-105.90083329999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.2575&lon=-105.90083329999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 24  of Group 5 | 37.99472222-108.0022222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.99472222&lon=-108.0022222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 25  of Group 5 | 40.93555556-102.5255556.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.93555556&lon=-102.5255556&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 26  of Group 5 | 39.29805556-102.8694444.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.29805556&lon=-102.8694444&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 27  of Group 5 | 40.52666667-104.865.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.52666667&lon=-104.865&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 28  of Group 5 | 39.64666667-105.01833329999998.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.64666667&lon=-105.01833329999998&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 29  of Group 5 | 38.46666667-102.2944444.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.46666667&lon=-102.2944444&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 30  of Group 5 | 39.54833333-107.65333329999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.54833333&lon=-107.65333329999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 31  of Group 5 | 38.12027778-105.41027779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.12027778&lon=-105.41027779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 32  of Group 5 | 39.69555556-105.7263889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.69555556&lon=-105.7263889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 33  of Group 5 | 39.65611111-106.08694440000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.65611111&lon=-106.08694440000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 34  of Group 5 | 37.81083333-107.6647222.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.81083333&lon=-107.6647222&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 35  of Group 5 | 39.14083333-104.0825.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.14083333&lon=-104.0825&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 36  of Group 5 | 39.22111111-106.93916670000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.22111111&lon=-106.93916670000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 37  of Group 5 | 37.66916667-106.64166670000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.66916667&lon=-106.64166670000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 38  of Group 5 | 37.405-102.6188889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.405&lon=-102.6188889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 39  of Group 5 | 37.11694444-104.5233333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.11694444&lon=-104.5233333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 40  of Group 5 | 40.47777778-106.8241667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.47777778&lon=-106.8241667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 41  of Group 5 | 40.62055556-103.1925.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.62055556&lon=-103.1925&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 42  of Group 5 | 39.30277778-102.6033333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.30277778&lon=-102.6033333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 43  of Group 5 | 38.23277778-103.6633333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.23277778&lon=-103.6633333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 44  of Group 5 | 39.93388889-105.1588889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.93388889&lon=-105.1588889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 45  of Group 5 | 38.01416667-103.6280556.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.01416667&lon=-103.6280556&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 46  of Group 5 | 37.93638889-107.82694440000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.93638889&lon=-107.82694440000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 47  of Group 5 | 39.91972222-104.94388889999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.91972222&lon=-104.94388889999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 48  of Group 5 | 40.53388889-104.96222220000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.53388889&lon=-104.96222220000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 49  of Group 5 | 37.175-104.49083329999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.175&lon=-104.49083329999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 0  of Group 6 | 37.56055556-102.3966667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.56055556&lon=-102.3966667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 1  of Group 6 | 39.63861111-106.3611111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.63861111&lon=-106.3611111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 2  of Group 6 | 38.70861111-105.14194440000001.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.70861111&lon=-105.14194440000001&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 3  of Group 6 | 37.37361111-102.4475.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.37361111&lon=-102.4475&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 4  of Group 6 | 39.30222222-102.7433333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.30222222&lon=-102.7433333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 5  of Group 6 | 40.73166667-106.2813889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.73166667&lon=-106.2813889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 6  of Group 6 | 37.63055556-104.7816667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.63055556&lon=-104.7816667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 7  of Group 6 | 37.38611111-102.28.
http://api.openweathermap.org/data/2.5/air_pollution?lat=37.38611111&lon=-102.28&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 8  of Group 6 | 40.07222222-105.5138889.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.07222222&lon=-105.5138889&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 9  of Group 6 | 40.7-105.00527779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.7&lon=-105.00527779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 10  of Group 6 | 38.13388889-105.4652778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.13388889&lon=-105.4652778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 11  of Group 6 | 39.88361111-105.0625.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.88361111&lon=-105.0625&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 12  of Group 6 | 39.77277778-105.1027778.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.77277778&lon=-105.1027778&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 13  of Group 6 | 40.22861111-104.0725.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.22861111&lon=-104.0725&appid=90d059c74bd13bcc4087b66e982c1bf1

Processing Record 14  of Group 6 | 38.15527778-102.7191667.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.15527778&lon=-102.7191667&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 15  of Group 6 | 38.38388889-105.1711111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.38388889&lon=-105.1711111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 16  of Group 6 | 40.46888889-104.92.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.46888889&lon=-104.92&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 17  of Group 6 | 39.87861111-105.78277779999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=39.87861111&lon=-105.78277779999999&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 18  of Group 6 | 38.99861111-105.05944440000002.
http://api.openweathermap.org/data/2.5/air_pollution?lat=38.99861111&lon=-105.05944440000002&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 19  of Group 6 | 40.08-102.2283333.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.08&lon=-102.2283333&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 20  of Group 6 | 40.15305556-106.9086111.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.15305556&lon=-106.9086111&appid=90d059c74bd13bcc4087b66e982c1bf1
Processing Record 21  of Group 6 | 40.12361111-102.71611109999999.
http://api.openweathermap.org/data/2.5/air_pollution?lat=40.12361111&lon=-102.71611109999999&appid=90d059c74bd13bcc4087b66e982c1bf1

In [6]:
print(air_df)

              City        Date      lat       lon AQI      CO NO   NO2  \
0          Aguilar  1628398800  37.4036 -104.6550   4  223.64  0  2.36
1            Akron  1628398800  40.1633 -103.2203   4  273.71  0  3.04
2          Alamosa  1628398800  37.4753 -105.8769   5  243.66  0  1.59
3             Alma  1628398800  39.2858 -106.0669   4  233.65  0  3.34
4         Antonito  1628398800  37.0761 -106.0103   5  280.38  0  1.34
..             ...         ...      ...       ...  ..     ... ..   ...
267    Winter Park  1628398800  39.8786 -105.7828   4  190.26  0  1.91
268  Woodland Park  1628398800  38.9986 -105.0594   5  290.39  0  2.38
269           Wray  1628398800  40.0800 -102.2283   5  323.77  0  2.72
270          Yampa  1628398800  40.1531 -106.9086   4  200.27  0  1.80
271           Yuma  1628398800  40.1236 -102.7161   4  273.71  0  3.26

         O3   SO2   PM25   PM10   NH3 Population
0     97.28  0.48  32.87  48.14  2.38        480
1     94.41  1.51  33.77  35.82  3.10      1,723
2    104.43  0.13  54.18  55.06  1.71      9,591
3     49.35  0.06  44.71  46.88  1.03        313
4     51.50  0.08  82.20  83.57  2.28        747
..      ...   ...    ...    ...   ...        ...
267   67.95  0.46  26.44  27.19  0.72      1,090
268   90.12  0.84  58.00  63.27  1.33      7,885
269  104.43  0.76  56.83  59.38  3.80      2,349
270   72.24  1.24  31.63  32.90  2.06        464
271   79.39  0.67  33.77  35.70  3.14      3,479

[272 rows x 14 columns]

In [7]:
# obtain datetime series:
datetimes = pd.to_datetime(air_df['Date'], unit='s')

# assign your new columns
air_df['Year'] = datetimes.dt.year
air_df['Month'] = datetimes.dt.month
air_df['Day'] = datetimes.dt.day
air_df['Hour'] = datetimes.dt.hour
air_df['Minute'] = datetimes.dt.minute

In [8]:
#Clean city names
air_df["City"] = air_df['City'].str.split('[').str[0]
air_df.head()

,City,Date,lat,lon,AQI,CO,NO,NO2,O3,SO2,PM25,PM10,NH3,Population,Year,Month,Day,Hour,Minute
0,Aguilar,1628398800,37.4036,-104.6550,4,223.64,0,2.36,97.28,0.48,32.87,48.14,2.38,480,2021,8,8,5,0
1,Akron,1628398800,40.1633,-103.2203,4,273.71,0,3.04,94.41,1.51,33.77,35.82,3.10,"1,723",2021,8,8,5,0
2,Alamosa,1628398800,37.4753,-105.8769,5,243.66,0,1.59,104.43,0.13,54.18,55.06,1.71,"9,591",2021,8,8,5,0
3,Alma,1628398800,39.2858,-106.0669,4,233.65,0,3.34,49.35,0.06,44.71,46.88,1.03,313,2021,8,8,5,0
4,Antonito,1628398800,37.0761,-106.0103,5,280.38,0,1.34,51.50,0.08,82.20,83.57,2.28,747,2021,8,8,5,0

In [9]:
#Export to CSV
air_df.to_csv('Resources/data/air_api_data.csv')
#Export DF to html file
air_df.to_html('Resources/webpages/air_api_data.html')

In [10]:
import pandas as pd
# import numpy as np

import sqlalchemy
from sqlalchemy import create_engine, func, inspect
from sqlalchemy.orm import Session

import sqlite3

# from sqlalchemy.ext.automap import automap_base
# from sqlalchemy.orm import Session
# import sqlite3

In [11]:
# airquality_df = pd.read_csv("./Resources/air_api_data.csv")
# airquality_df

In [12]:
conn = sqlite3.connect('./Resources/air.sqlite')

# engine = create_engine('sqlite:///Resources/air.sqlite')

In [13]:
air_df.to_sql(name = 'airquality', con = conn, if_exists='replace', index=False)

In [14]:
cur = conn.cursor()

In [15]:
cur.execute("select * from airquality limit 5;")

In [16]:
results = cur.fetchall()
print(results)

[('Aguilar', 1628398800, 37.4036, -104.655, 4, 223.64, '0', 2.36, 97.28, 0.48, 32.87, 48.14, 2.38, '480', 2021, 8, 8, 5, 0), ('Akron', 1628398800, 40.1633, -103.2203, 4, 273.71, '0', 3.04, 94.41, 1.51, 33.77, 35.82, 3.1, '1,723', 2021, 8, 8, 5, 0), ('Alamosa', 1628398800, 37.4753, -105.8769, 5, 243.66, '0', 1.59, 104.43, 0.13, 54.18, 55.06, 1.71, '9,591', 2021, 8, 8, 5, 0), ('Alma', 1628398800, 39.2858, -106.0669, 4, 233.65, '0', 3.34, 49.35, 0.06, 44.71, 46.88, 1.03, '313', 2021, 8, 8, 5, 0), ('Antonito', 1628398800, 37.0761, -106.0103, 5, 280.38, '0', 1.34, 51.5, 0.08, 82.2, 83.57, 2.28, '747', 2021, 8, 8, 5, 0)]

In [17]:
airquality_table = pd.read_sql_query("SELECT * FROM airquality", conn)
airquality_table.head(5)

,City,Date,lat,lon,AQI,CO,NO,NO2,O3,SO2,PM25,PM10,NH3,Population,Year,Month,Day,Hour,Minute
0,Aguilar,1628398800,37.4036,-104.6550,4,223.64,0,2.36,97.28,0.48,32.87,48.14,2.38,480,2021,8,8,5,0
1,Akron,1628398800,40.1633,-103.2203,4,273.71,0,3.04,94.41,1.51,33.77,35.82,3.10,"1,723",2021,8,8,5,0
2,Alamosa,1628398800,37.4753,-105.8769,5,243.66,0,1.59,104.43,0.13,54.18,55.06,1.71,"9,591",2021,8,8,5,0
3,Alma,1628398800,39.2858,-106.0669,4,233.65,0,3.34,49.35,0.06,44.71,46.88,1.03,313,2021,8,8,5,0
4,Antonito,1628398800,37.0761,-106.0103,5,280.38,0,1.34,51.50,0.08,82.20,83.57,2.28,747,2021,8,8,5,0

In [18]:
for row in cur.execute("SELECT name FROM sqlite_master WHERE type='table';"):
    print(row)

('airquality',)

In [19]:
# airquality_table = pd.read_sql_query("SELECT * FROM airquality", conn)
# airquality_table.head(5)

In [20]:
airquality_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 272 entries, 0 to 271
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        272 non-null    object
 1   Date        272 non-null    int64
 2   lat         272 non-null    float64
 3   lon         272 non-null    float64
 4   AQI         272 non-null    int64
 5   CO          272 non-null    float64
 6   NO          272 non-null    object
 7   NO2         272 non-null    float64
 8   O3          272 non-null    float64
 9   SO2         272 non-null    float64
 10  PM25        272 non-null    float64
 11  PM10        272 non-null    float64
 12  NH3         272 non-null    float64
 13  Population  272 non-null    object
 14  Year        272 non-null    int64
 15  Month       272 non-null    int64
 16  Day         272 non-null    int64
 17  Hour        272 non-null    int64
 18  Minute      272 non-null    int64
dtypes: float64(9), int64(7), object(3)
memory usage: 40.5+ KB

In [21]:
airquality_table.head()

,City,Date,lat,lon,AQI,CO,NO,NO2,O3,SO2,PM25,PM10,NH3,Population,Year,Month,Day,Hour,Minute
0,Aguilar,1628398800,37.4036,-104.6550,4,223.64,0,2.36,97.28,0.48,32.87,48.14,2.38,480,2021,8,8,5,0
1,Akron,1628398800,40.1633,-103.2203,4,273.71,0,3.04,94.41,1.51,33.77,35.82,3.10,"1,723",2021,8,8,5,0
2,Alamosa,1628398800,37.4753,-105.8769,5,243.66,0,1.59,104.43,0.13,54.18,55.06,1.71,"9,591",2021,8,8,5,0
3,Alma,1628398800,39.2858,-106.0669,4,233.65,0,3.34,49.35,0.06,44.71,46.88,1.03,313,2021,8,8,5,0
4,Antonito,1628398800,37.0761,-106.0103,5,280.38,0,1.34,51.50,0.08,82.20,83.57,2.28,747,2021,8,8,5,0

In [22]:
AQI_2 = pd.read_sql_query("SELECT * FROM airquality WHERE AQI >= 2 ", conn)
AQI_2

,City,Date,lat,lon,AQI,CO,NO,NO2,O3,SO2,PM25,PM10,NH3,Population,Year,Month,Day,Hour,Minute
0,Aguilar,1628398800,37.4036,-104.6550,4,223.64,0,2.36,97.28,0.48,32.87,48.14,2.38,480,2021,8,8,5,0
1,Akron,1628398800,40.1633,-103.2203,4,273.71,0,3.04,94.41,1.51,33.77,35.82,3.10,"1,723",2021,8,8,5,0
2,Alamosa,1628398800,37.4753,-105.8769,5,243.66,0,1.59,104.43,0.13,54.18,55.06,1.71,"9,591",2021,8,8,5,0
3,Alma,1628398800,39.2858,-106.0669,4,233.65,0,3.34,49.35,0.06,44.71,46.88,1.03,313,2021,8,8,5,0
4,Antonito,1628398800,37.0761,-106.0103,5,280.38,0,1.34,51.50,0.08,82.20,83.57,2.28,747,2021,8,8,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,Winter Park,1628398800,39.8786,-105.7828,4,190.26,0,1.91,67.95,0.46,26.44,27.19,0.72,"1,090",2021,8,8,5,0
238,Woodland Park,1628398800,38.9986,-105.0594,5,290.39,0,2.38,90.12,0.84,58.00,63.27,1.33,"7,885",2021,8,8,5,0
239,Wray,1628398800,40.0800,-102.2283,5,323.77,0,2.72,104.43,0.76,56.83,59.38,3.80,"2,349",2021,8,8,5,0
240,Yampa,1628398800,40.1531,-106.9086,4,200.27,0,1.80,72.24,1.24,31.63,32.90,2.06,464,2021,8,8,5,0
241,Yuma,1628398800,40.1236,-102.7161,4,273.71,0,3.26,79.39,0.67,33.77,35.70,3.14,"3,479",2021,8,8,5,0

In [23]:
# engine = create_engine('sqlite:///Resources/air.sqlite')
# conn = engine.connect()

In [24]:
# air_df.to_sql('airquality', conn, if_exists='replace', index=False)

In [25]:
# inspector=inspect(engine)
# inspector.get_table_names()

In [26]:
# conn.execute('pragma table_info(airquality);').fetchall()

In [27]:
# conn.execute('select * from airquality limit 10').fetchall()

In [28]:
conn.close()

###